{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "db-monitor.serviceAccountName" . }}
  labels:
    {{- include "db-monitor.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
